name: Rollback

on: 
  workflow_dispatch:
    # inputs 下面可以指定要手动输入的信息
    inputs:
      version:
        description: "Choose a version to deploy"
        required: true

jobs:
  Rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Echo version
        env: 
          VERSION: ${{github.event.inputs.version}}
        run: echo "version: $VERSION"
      - name: End
        run: echo "Do your rollback actions"